version: '2.1'
services:
  web:
    build: .
    ports:
    - 8080-8081:8080
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: docker
  mongo:
    container_name: springboot-mongo
    image: bitnami/mongodb:latest
    ports:
    - "27017:27017"